### PR TITLE
ORSet

### PR DESCRIPTION
**Pull request by nick-loginov**
This change is [Reviewable](https://reviewable.io/reviews/cblp/crdt/13)

### CODE REVIEW

**Comment by cblp** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/CRDT/Cv/ORSet.hs, line 21 at r1](https://reviewable.io:443/reviews/cblp/crdt/13#-KyjgAPWRFLuMkWDC-qb:-KyjgAPWRFLuMkWDC-qc:b-i6f94i) ([raw file](https://github.com/cblp/crdt/blob/399791c5ad54af0ebe76bb1bd45fc13c358b4b52/lib/CRDT/Cv/ORSet.hs#L21)):*
> ```Haskell
> 
> newtype ORSet a = ORSet (Map Pid (Set a))
>     deriving (Eq, Ord, Show)
> ```

Зачем Ord?

---

*[test/ORSet.hs, line 18 at r1](https://reviewable.io:443/reviews/cblp/crdt/13#-KyjgsY5ChAoTMkt2JVS:-KyjgsY5ChAoTMkt2JVT:b98jirv) ([raw file](https://github.com/cblp/crdt/blob/399791c5ad54af0ebe76bb1bd45fc13c358b4b52/test/ORSet.hs#L18)):*
> ```Haskell
> test_Cv = cvrdtLaws @(ORSet Int)
> 
> prop_insert = property $ \(pid :: Pid) i ->
> ```

кажется, здесь тип pid можно не указывать

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cblp/crdt/13)*

**Comment by nick-loginov** [comment]
*[test/ORSet.hs, line 18 at r1](https://reviewable.io:443/reviews/cblp/crdt/13#-KyjgsY5ChAoTMkt2JVS:-Kyjn5aMYg28utEDiQm9:b92mp7g) ([raw file](https://github.com/cblp/crdt/blob/399791c5ad54af0ebe76bb1bd45fc13c358b4b52/test/ORSet.hs#L18)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

кажется, здесь тип pid можно не указывать
</blockquote></details>

Да, верно, исправлю

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cblp/crdt/13)*

**Comment by nick-loginov** [comment]
*[lib/CRDT/Cv/ORSet.hs, line 21 at r1](https://reviewable.io:443/reviews/cblp/crdt/13#-KyjgAPWRFLuMkWDC-qb:-KyjnCzaOIe7B4pjVZqJ:b-vi4ki5) ([raw file](https://github.com/cblp/crdt/blob/399791c5ad54af0ebe76bb1bd45fc13c358b4b52/lib/CRDT/Cv/ORSet.hs#L21)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Зачем Ord?
</blockquote></details>

От страха написал

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cblp/crdt/13)*

**Comment by cblp** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/CRDT/Cv/ORSet.hs, line 21 at r1](https://reviewable.io:443/reviews/cblp/crdt/13#-KyjgAPWRFLuMkWDC-qb:-Kyjnx3cuRkM1aMFbb5T:bf0e7gy) ([raw file](https://github.com/cblp/crdt/blob/399791c5ad54af0ebe76bb1bd45fc13c358b4b52/lib/CRDT/Cv/ORSet.hs#L21)):*
<details><summary><i>Previously, kemphack wrote…</i></summary><blockquote>

От страха написал
</blockquote></details>

убери от страха

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cblp/crdt/13)*

**Comment by cblp** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/ORSet.hs, line 1 at r2](https://reviewable.io:443/reviews/cblp/crdt/13#-Kyjuey7ukLFofH_CC6U:-Kyjuey7ukLFofH_CC6V:b-8dlmfv) ([raw file](https://github.com/cblp/crdt/blob/d269ab638397879ca12e10cadc24dff479f2cbb0/test/ORSet.hs#L1)):*
> ```Haskell
> {-# OPTIONS_GHC -Wno-missing-signatures #-}
> ```

Надо добавить вот такой тест-свойство:

```haskell
\s0 s2 x pid -> let s1 = add pid x s; in lookup x (s1 <> s2)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cblp/crdt/13)*

**Comment by cblp** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cblp/crdt/13)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/ORSet.hs, line 1 at r2](https://reviewable.io:443/reviews/cblp/crdt/13#-Kyjuey7ukLFofH_CC6U:-KyjvSHKBHuGnfN21XH1:bbsizj3) ([raw file](https://github.com/cblp/crdt/blob/d269ab638397879ca12e10cadc24dff479f2cbb0/test/ORSet.hs#L1)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Надо добавить вот такой тест-свойство:

```haskell
\s0 s2 x pid -> let s1 = add pid x s; in lookup x (s1 <> s2)
```
</blockquote></details>

```haskell
\s0 s2 x pid -> let s1 = add pid x s0 in lookup x (s1 <> s2)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cblp/crdt/13)*

**Comment by cblp** [comment]
Reviewed 1 of 2 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cblp/crdt/13)*

**Comment by cblp** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cblp/crdt/13)*

**Pull request merged**
